#!/bin/sh
# Helper script invoked by `make nginx-config` to generate an Nginx stream config.
# It uses environment variables passed from Makefile.
set -eu

if [ -z "${DOMAIN:-}" ]; then
  echo "ERROR: DOMAIN is required. Example: make nginx-config DOMAIN=queue.example.com" >&2
  exit 1
fi

# Determine destination directory if not provided; pick the first existing
dest_dir="${NGINX_STREAM_DIR:-}"
if [ -z "$dest_dir" ]; then
  for d in /etc/nginx/streams-enabled /etc/nginx/stream.d /etc/nginx/conf.d /etc/nginx/sites-enabled; do
    if [ -d "$d" ]; then dest_dir="$d"; break; fi
  done
fi
if [ -z "$dest_dir" ]; then
  echo "ERROR: Could not detect an Nginx stream config directory." >&2
  echo "Please create one and pass NGINX_STREAM_DIR=/path/to/dir" >&2
  exit 1
fi

# Determine certificate paths
fullchain="${CERT_FULLCHAIN:-}"
privkey="${CERT_KEY:-}"
if [ -z "$fullchain" ] || [ -z "$privkey" ]; then
  cert_dir="${CERT_DIR:-}"
  if [ -z "$cert_dir" ]; then cert_dir="/etc/letsencrypt/live/${DOMAIN}"; fi
  fullchain="${cert_dir}/fullchain.pem"
  privkey="${cert_dir}/privkey.pem"
fi

# Defaults
LISTEN_PORT="${LISTEN_PORT:-5671}"
BACKEND_HOST="${BACKEND_HOST:-127.0.0.1}"
BACKEND_PORT="${BACKEND_PORT:-5672}"
NGINX_CONFIG_NAME="${NGINX_CONFIG_NAME:-nginx-rabbitmq-${DOMAIN}.conf}"
NGINX_TEST="${NGINX_TEST:-nginx -t}"
NGINX_RELOAD="${NGINX_RELOAD:-nginx -s reload}"

cfg_path="${dest_dir}/${NGINX_CONFIG_NAME}"
echo "Generating Nginx stream config at: ${cfg_path}"

umask 022
cat >"${cfg_path}" <<EOF_CFG
# Auto-generated by Makefile (nginx-config)
# AMQPS (TLS) listener for ${DOMAIN} on port ${LISTEN_PORT},
# terminating TLS and forwarding to HAProxy at ${BACKEND_HOST}:${BACKEND_PORT}

upstream amqp_backend {
    server ${BACKEND_HOST}:${BACKEND_PORT};
}

server {
    listen 0.0.0.0:${LISTEN_PORT} ssl;
    ssl_certificate     ${fullchain};
    ssl_certificate_key ${privkey};

    # Harden TLS (adjust if legacy clients require older protocols/ciphers)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers   HIGH:!aNULL:!MD5;

    # AMQP connections are long-lived
    proxy_connect_timeout 5s;
    proxy_timeout 3h;

    proxy_pass amqp_backend;
}
EOF_CFG

# Test and reload Nginx
echo "Testing Nginx configuration..."
if ! sh -c "$NGINX_TEST"; then
  echo "ERROR: Nginx config test failed. Not reloading." >&2
  exit 1
fi

echo "Reloading Nginx..."
sh -c "$NGINX_RELOAD"

echo "Done. Clients can connect via amqps://USER:PASS@${DOMAIN}:${LISTEN_PORT}/VHOST"
